### ISSUE TITLE
How to install this module?

### ISSUE THREAD

**Issue by mark22** [hyperlab/TiImageCropper#4]
Hi I guess I'm a newbie in this sense, but for all the other modules I use, I simply download the ZIP from github, goto the DIST directory and unpackaged the zip and install it into my modules folder.

However, here we don't have any kind of DIST directory.  Is there an idea of how I can install this module

Thank you !!

**Comment by jonatansberg** [comment]
No worries!

The releases are available though gittio as well as here on github in the releases section:
https://github.com/hyperlab/TiImageCropper/releases
