### ISSUE TITLE
Zoomout is not working for iOS.

### ISSUE THREAD

**Issue by pravin-mindstix** [hyperlab/TiImageCropper#8]
Hi,
Module is awesome.
Zoom In is possible in this module but I am not able to do Zoom out. (I mean to say I want to put whole image in square)
Or is there any way to increase size of square ?

```
mageCropper.open({
                    image : currentMedia,
                    size : 1000,
                    height : 120,
                    width : 100,
```

I tired but no effects.
Is there any way to do it?

Thanks,

**Comment by jonatansberg** [comment]
Hi there Parvin,
The iOS module only crops to squares and tries to make sure that the entire square is covered. This is usually what you'd want for profile images and such (and what we created this module to solve.) If you want another behaviour you will need to expose the appropriate APIs from RSKImageCropper by extending the module.

All the best,
Jonatan Lundin

**Comment by pravin-mindstix** [comment]
Thanks Jonatan for replying.

Will try to explore it.
